using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Windows.Forms;
using System.Xml;

namespace Dynamic.Script_8D5B65FEC42AD8F
{
	// Script generated by Pega Robotics Studio 8.0.1087.0
	// Please use caution when modifying class name, namespace or attributes
	[OpenSpan.TypeManagement.DynamicTypeAttribute()]
	[OpenSpan.Design.ComponentIdentityAttribute("Script-8D5B65FEC42AD8F")]
	public sealed class Script
	{
		public string NumberToCell(int number)
		{
			int asciiA = 65;
			int asciiZ = 90;

			int asciiNumber = asciiA + (number - 1);
			char c = Convert.ToChar(asciiNumber);
			return c + "";
		}
	}
}
